### ISSUE TITLE
1.20.1 spigot 出现异常问题

### ISSUE THREAD

**Issue by VOLLEY888** [xiaocheng168/FastAfk#2]
```
afk:
  #领地名 子领地用下划线分割
  newspawn_afk:
    #是否启用
    enable: true
    #权限节点 为空则不需要权限
    permission: ""
    #单位 （ms）
    delay: 30000
    #给的金币
    money: 10
    #给的点券
    points: 0
    #给的经验
    exp: 3
    #进入提示 Title
    join_title: "§a你已进入挂机池"
    join_sub_title: "§a你已进入挂机池"
    #奖励发放提示 Title
    give_award_title: "§e奖励已发放"
    give_award_sub_title: ""
    #进入后没有权限提示 Title
    no_permission_title: "§c没有权限欸"
    no_permission_sub_title: ""
    #执行的命令
    commands:
      - ""
``` 

领地名newspawn.afk
后台刷报错：[FastAfk] 无法导入该命令 未知命令类型: newspawn_afk 原格式:
